//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PIDPC.rc
//
#define IDC_BUTTON_CLOSE                2
#define IDD_Page1                       9
#define IDD_ABOUTBOX                    99
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_MAIN_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_Page2                       132
#define IDB_LED_GREY                    134
#define IDB_LED_GREEN                   135
#define IDD_Page3                       137
#define IDR_MENU1                       138
#define IDD_Page4                       138
#define IDR_MENU3                       140
#define IDR_MENU4                       141
#define IDD_PID_TEST_DIALOG             142
#define IDD_MONITOR_TEMPR               143
#define IDD_Page5                       144
#define IDD_REFLOW_SETUP_DIALOG         145
#define IDD_Page6                       146
#define IDD_SENSOR_SETUP_DIALOG         147
#define IDB_TS_SCH                      152
#define IDB_LED_RED                     153
#define IDB__LED_YELLOW                 154
#define IDD_DIALOG_BLE                  156
#define IDC_RADIO_PID_MODE_AUTO         1001
#define IDC_TAB1                        1003
#define IDC_RADIO_PID_MODE_MANUAL       1004
#define IDC_COMBO_TYPES                 1005
#define IDC_STATIC_CH1_KP               1027
#define IDC_STATIC_CH1_KI               1028
#define IDC_STATIC_CH1_KD               1029
#define IDC_STATIC_CH1_KP2              1030
#define IDC_STATIC_DAC_OUT_PER          1031
#define IDC_EDIT_KP                     1033
#define IDC_EDIT_KI                     1034
#define IDC_EDIT_KD                     1035
#define IDC_CHECK_MANUAL                1036
#define IDC_EDIT_FAN_GAIN               1037
#define IDC_EDIT_REF                    1039
#define IDC_STATIC_CHN                  1051
#define IDC_BUTTON_SETCHNDEFAULT        1054
#define IDC_STATIC_CH1_KD2              1058
#define IDC_STATIC_DEVICE_TXT           1070
#define IDC_STATIC_1                    1075
#define IDC_STATIC_2                    1076
#define IDC_STATIC_3                    1077
#define IDC_STATIC_4                    1078
#define IDC_EDIT_PID_PERIOD             1087
#define IDC_COMBO_MEASURE_RES           1091
#define IDC_COMBO_BURST                 1092
#define IDC_COMBO_AMBIENT_RES           1093
#define IDC_COMBO_MODE                  1094
#define IDC_EDIT_CALIBR                 1095
#define IDC_STATIC_PIC_ALERT1           1096
#define IDC_STATIC_PIC_ALERT2           1097
#define IDC_STATIC_PIC_ALERT3           1098
#define IDC_STATIC_PIC_ALERT4           1099
#define IDC_STATIC_PIC_IR               1100
#define IDC_STATIC_PIC_THU              1101
#define IDC_STATIC_PIC_BMC              1102
#define IDC_STATIC_HELP8                1127
#define IDC_STATIC_HELP9                1128
#define IDC_BUTTON_UPDATE               1130
#define IDC_BUTTON_SET_DEFAULT          1134
#define IDC_SLIDER_HEATER               1156
#define IDC_SLIDER_FAN                  1157
#define IDC_COMBO_FILTER                1163
#define IDC_BUTTON_TEST_MEANDER         1166
#define IDC_STATIC_DEVICE_LED           1169
#define IDC_PROGRESS_TMPR               1186
#define IDC_PROGRESS_CURR               1187
#define IDC_COMBO_PCR_WRITE             1196
#define IDC_BUTTON_WRITE_PROFILE        1206
#define IDC_EDIT_MONITOR                1207
#define IDC_BUTTON_FOPEN_PCR            1208
#define IDC_BUTTON_SHOW_GRAPH           1209
#define IDC_PROGRESS_WRITE              1212
#define IDC_BUTTON_REFLOW_RUN           1213
#define IDC_BUTTON_ANALYSIS             1214
#define IDC_BUTTON_FROM_BEGIN           1215
#define IDC_BUTTON_READ_SETUP           1217
#define IDC_SCROLLBAR1                  1220
#define IDC_BUTTON_FSAVE_PCR            1221
#define IDC_BUTTON_READ_PROFILE         1223
#define IDC_BUTTON_SHOW_FILE            1224
#define IDC_EDIT_MAX_POWER              1225
#define IDC_EDIT_MAX_TMPR               1226
#define IDC_EDIT_FAN                    1227
#define IDC_STATIC5                     1228
#define IDC_EDIT_HEATER_PWR             1229
#define IDC_STATIC_WARNINGS             1232
#define IDC_PROGRESS_FAN                1233
#define IDC_STATIC_TEMPERATURE_VAL      1239
#define IDC_STATIC_POWER_VAL            1242
#define IDC_BUTTON_RESET                1251
#define IDC_BUTTON_CONSOLE_CLS          1264
#define IDC_BUTTON_TEST_LINERITY        1265
#define IDC_STATIC_TXT_GRAD             1268
#define IDC_CHECK_SHOW_LOG              1274
#define IDC_CHECK_DATA_TXT_LOG          1275
#define IDC_STATIC_PAGE                 1281
#define IDC_STATIC_TXT1                 1282
#define IDC_STATIC_TXT12                1283
#define IDC_COMBO_TEST_FUNCTION         1299
#define IDC_STATIC_0                    1300
#define IDC_EDIT_MAX_VALUE              1301
#define IDC_EDIT_MIN_VALUE              1302
#define IDC_EDIT_CYCLES                 1303
#define IDC_EDIT_CYCLES2                1304
#define IDC_BUTTON_TEST_ONOFF           1305
#define IDC_BUTTON_PANEL                1308
#define IDC_PROGRESS_HEATER             1309
#define IDC_STATIC_T                    1310
#define IDC_STATIC_TEMPERATURE          1310
#define IDC_STATIC_C                    1311
#define IDC_STATIC_HEATER               1311
#define IDC_PROGRESS_TEMPERATURE        1312
#define IDC_STATIC_FAN                  1313
#define IDC_BUTTON_TEST_STEP            1318
#define IDC_BUTTON_SETTINGS             1337
#define IDC_BUTTON_PCR_PAUSE            1338
#define IDC_BUTTON_PID_MANUAL_RUN       1347
#define IDC_BUTTON_BT_INFO              1385
#define IDC_BUTTON_BT                   1385
#define IDC_BUTTON_FW_INFO              1391
#define IDC_BUTTON_HELP                 1392
#define IDC_BUTTON_PROFILE_LIST         1393
#define IDC_BUTTON_SENSORS_LIST         1394
#define IDC_BUTTON_SHOW_EEPROM          1395
#define IDC_BUTTON_SHOW_SETTINGS        1396
#define IDC_BUTTON_EEPROM_TEST          1397
#define IDC_CHECK_TS_TOP_LEFT           1398
#define IDC_BUTTON_ABOUT                1398
#define IDC_STATIC_TOP                  1399
#define IDC_BUTTON_CURR_PROFILE         1399
#define IDC_CHECK_TS_TOP_RIGHT          1400
#define IDC_BUTTON_ERASE_CUSTOM_PR      1400
#define IDC_COMBO_HTR_CALC              1401
#define IDC_STATIC_EXTRA_SENSORS        1402
#define IDC_CHECK_TS1                   1403
#define IDC_CHECK_TS2                   1404
#define IDC_CHECK_TS3                   1405
#define IDC_CHECK_TS4                   1406
#define IDC_COMBO_TS1                   1407
#define IDC_COMBO_TS2                   1408
#define IDC_COMBO_TS3                   1409
#define IDC_COMBO_TS4                   1410
#define IDC_COMBO_TS_CALC               1411
#define IDC_BUTTON_CFG_TS1              1412
#define IDC_BUTTON_CFG_TS2              1413
#define IDC_STATIC_PICTURE              1413
#define IDC_BUTTON_CFG_TS3              1414
#define IDC_EDIT_OFFSET1                1414
#define IDC_BUTTON_CFG_TS4              1415
#define IDC_EDIT_OFFSET2                1415
#define IDC_EDIT_DGAIN1                 1416
#define IDC_EDIT_DGAIN2                 1417
#define IDC_STATIC_TXTMSG               1419
#define IDC_STATIC_TOUT1                1420
#define IDC_STATIC_TOUT2                1421
#define IDC_BUTTON_EEPROM_ERASE         1421
#define IDC_STATIC_H                    1422
#define IDC_STATIC_TCJ                  1422
#define IDC_STATIC_F                    1423
#define IDC_STATIC_P1                   1425
#define IDC_STATIC_txt45                1426
#define IDC_CHECK_LOG_FIX               1427
#define IDC_BUTTON_AUTO_TUNE            1428
#define IDC_STATIC_TXT_BUILD            1429
#define IDC_CHECK_PRH_ON                1430
#define IDC_EDIT_PREHIT_TIME            1431
#define IDC_EDIT_PREHIT_TEMPR           1433
#define IDC_EDIT_PAUSE_TIME             1434
#define IDC_STATIC_TXT_PS               1435
#define IDC_STATIC_sd                   1436
#define IDC_CHECK_ALG_SN1               1437
#define IDC_CHECK_ALG_SN2               1438
#define IDC_CHECK_ALG_SN3               1439
#define IDC_CHECK_ALG_SN4               1440
#define IDC_COMBO_ALG_MODE              1443
#define IDC_EDIT_INFO                   1445
#define IDC_EDIT_COM                    1445
#define IDC_FW_PROGRESS                 1446
#define IDC_BUTTON_CONNECT              1451
#define IDC_BUTTON_SCAN                 1452
#define IDC_BUTTON_DISCONNECT           1453
#define IDC_LIST1                       1454
#define IDC_EDIT_ADDR                   1455
#define IDC_BUTTON_COM                  1456
#define IDC_COMBO_TX_POWER              1458
#define IDC_COMBO_RX_GAIN               1459
#define IDC_STATIC_RX                   1460
#define IDC_CHECK_LOG1                  1461
#define IDC_CHECK_LOG2                  1462
#define IDC_CHECK_LOG3                  1463
#define IDC_CHECK_LOG4                  1464
#define IDC_CHECK_LOG5                  1465
#define IDC_CHECK_LOG6                  1466
#define IDC_CHECK_LOG7                  1467
#define IDC_CHECK_LOG8                  1468
#define IDC_CHECK_LOG9                  1469
#define ID_PAGE5_ADDVERTEX              32775
#define ID_PAGE5_DELETESEGMENT          32776
#define ID_PAGE5_DELETEVERTEX           32778
#define ID__COPYSECTION                 32780
#define ID_CONNECT_CH1                  32790
#define ID_CONNECT_CH2                  32791
#define ID_CONNECT_CH3                  32792
#define ID_CONNECT_CH4                  32793
#define ID_CONNECT_CH5                  32794
#define ID_CONNECT_CH6                  32795
#define ID_DISABLE_CHN                  32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1462
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
